#Configuracion
#Mon May 18 00:05:18 MST 2026
principal.window.height=500
principal.window.width=1200
principal.window.x=168
principal.window.y=206
registration.window.height=500
registration.window.width=1100
registration.window.x=218
registration.window.y=206
ui.theme=light
